In [25]:
import numpy as np
from datetime import datetime, timedelta, date

In [26]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr[0][0]

array([1, 2, 3])

In [29]:
arr[0][0][1]

2

In [30]:
def calculate_age_with_datetime(birth_date):
    """Calculates age in years, months, and days using the built-in datetime module."""
    today = date.today()
    print(today)    
    # Calculate initial year difference
    years = today.year - birth_date.year
    
    # Adjust for cases where the birthday has not yet occurred this year
    months = today.month - birth_date.month
    days = today.day - birth_date.day
    
    if days < 0:
        months -= 1
        # Handle the number of days in the previous month
        last_month = today.replace(day=1) - date.resolution
        days += last_month.day
        
    if months < 0:
        years -= 1
        months += 12
        
    return years, months, days

# Example usage
birth_date = date(1994, 5, 27)
years, months, days = calculate_age_with_datetime(birth_date)
print(f"Age: {years} years, {months} months, {days} days")

2025-10-26
Age: 31 years, 4 months, 29 days


In [31]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [32]:
copyArr = arr.copy()
copyArr

array([1, 2, 3, 4, 5])

In [33]:
copyArr[0] = 20

In [34]:
print(f"Original Array : {arr}")
print(f"Copy Array : {copyArr}")

Original Array : [1 2 3 4 5]
Copy Array : [20  2  3  4  5]


In [35]:
print(f"Membership of Original Array : {arr.base}")
print(f"Membership of Copy Array : {copyArr.base}")

Membership of Original Array : None
Membership of Copy Array : None


In [36]:
viewArr = arr.view()
viewArr

array([1, 2, 3, 4, 5])

In [37]:
viewArr[0] = 100

In [38]:
print(f"Original Array : {arr}")
print(f"View Array : {viewArr}")

Original Array : [100   2   3   4   5]
View Array : [100   2   3   4   5]


In [39]:
print(f"Membership of Original Array : {arr.base}")
print(f"Membership of View Array : {viewArr.base}")

Membership of Original Array : None
Membership of View Array : [100   2   3   4   5]
